### ISSUE TITLE
Error when running for the first time: corvid folder doesn't exist in Temp

### ISSUE THREAD

**Issue by selimnahimi** [KILLTUBE/corvid#1]
I've encountered this bug while running the program for the first time. The program tries to delete the corvid folder in Temp, which initially doesn't exist, hence it throws an error. This can be fixed with a simple check for its existence.

ps. I hope you don't mind issues being reported, as I'm aware that it's still in development. I hope I can help with this.

**Comment by myuce** [comment]
Should be fixed after bfed2192316057ec3f8ffa282f2edb7029a21f3d. Thanks for letting me know.

> ps. I hope you don't mind issues being reported, as I'm aware that it's still in development. I hope I can help with this.

Of course I don't. This is the reason I made the repository avabilable for everyone in the first place. I can't think of every possibility  when it comes to bugs and features, so I'm open to ideas from everyone. Thanks for taking your time to try and do something with the tool!
