### ISSUE TITLE
'vpk is not a valid file'

### ISSUE THREAD

**Issue by HellboyDML** [KILLTUBE/corvid#10]
Hello! While compiling the map, I get this error of "'pak01_dir.vpk' is not a valid file!" I can't seem to figure out what the problem was. 

![image](https://user-images.githubusercontent.com/82686121/115096008-74ded680-9ef1-11eb-82b8-96b93a4b0156.png)

**Comment by myuce** [comment]
Corvid looks for those files in where Steam is installed. I have not added support for alternative library folders yet, so that's probably why you're getting that error. You can set the game profile to <none> and add the file `pak01_dir.vpk` manually just like you did it with the asset directories.

**Comment by myuce** [comment]
This issue should be fixed after cea6339a140b5e5c64ab48f6214db13f7df5e334. Corvid is now able to detect the Steam installation folder automatically and it also detects the other folders where games are installed.
