### ISSUE TITLE
Brushes get converted with Caulk texture. Textures are then added with textured no-collision planes.

### ISSUE THREAD

**Issue by Muhlex** [KILLTUBE/corvid#13]
Is this intended? In the example video you made, this doesn't seem to happen. You can see the two surfaces z-fighting here:

![screenshot](https://user-images.githubusercontent.com/21311428/140654296-23dab21f-c112-417c-b8a2-1ae2af16b52d.png)

The actual brushes are not converted with the correct texture. They just have the caulk texture. Then additionally for each brush all of the sides are represented with planes with the correct texture on. Is there a reason the brush can't just have the correct texture? Does this not usually happen? The map I'm converting does not use displacements in Hammer for anything.

EDIT: Just realized, this might be what you mean with `(converted as patch meshes to have accurate UVs)`. In that case, I guess this might just be a limitation of the current version and not really a bug of some sorts. In that case feel free to close. I just assumed brush UVs could be set just as one can in Hammer. I'm not very familiar with the CoD map formats.

**Comment by myuce** [comment]
You are correct. That's how plain brushes get converted. The way Valve games store texture alignment information is very different compared to how CoD does it, so I had to calculate brush geometry and create patch meshes with appropriate UVs. The brushes are still there to help with portalling. You can simply disable caulk from filters to avoid seeing them.

I've actually been looking for ways to convert brushes properly without having to use patch meshes, so I thought I could use [io_export_qmap](https://github.com/c-d-a/io_export_qmap/blob/master/io_export_qmap.py) as a reference, but I got sidetracked by some other projects and personal stuff. I'll try and see what I can do this week.
