### ISSUE TITLE
convertLight error when _light doesn't have a fourth color property

### ISSUE THREAD

**Issue by selimnahimi** [KILLTUBE/corvid#2]
in MapExporter.py, around line 274, rarely there's a case when an entity's _light property has 3 numbers. I've encountered this with the maps cs_italy (Counter-Strike: Source version) and gm_bigcity.
An example is shown in the attached picture:
![image](https://user-images.githubusercontent.com/21970287/111882472-1982fc80-89b6-11eb-8884-dedd13571012.png)

The program throws an error when in convertLight in MapExporter.py tries to set the "radius" property to _color[3], which in this case is out of bounds.

I managed to overcome this issue in a rough way, by setting the fourth property to a constant number in such cases.

**Comment by myuce** [comment]
Should be fixed after bfed2192316057ec3f8ffa282f2edb7029a21f3d. Thanks for letting me know.
