### ISSUE TITLE
Vec3#equals compares string/number

### ISSUE THREAD

**Issue by kungfooman** [KILLTUBE/corvid#2]
![image](https://user-images.githubusercontent.com/5236548/100602648-7756e000-3304-11eb-8be2-a7fde5b58c57.png)

`toFixed(2)` returns a string, which is then checked against `<= 0.01`

**Comment by myuce** [comment]
Fixed with [ccda5f8](https://github.com/KILLTUBE/corvid/commit/ccda5f8ba2d2ae44c633549a66c29b8b6faede32)
