### ISSUE TITLE
Possible malware?

### ISSUE THREAD

**Issue by FrozenDragon0** [KILLTUBE/corvid#30]
Ello, so I came across this tool when searching up things relating to porting source engine maps over into the BO3 mod tools and when I first heard of this I figured it sounded neat, however me being the paranoid person I am when it comes to .exe files I did run the corvid.exe through VirusTotal and I didn't like the results:
![image](https://user-images.githubusercontent.com/18079316/207628085-c1448f7b-b6ae-400c-9e4d-7abbda5c4419.png)

Again maybe it's just me being paranoid and these are possibly false detections but I just wanted to open this issue on here and get some clarification is all :)

**Comment by myuce** [comment]
Corvid is written in Python, so in order to make it work on other people's computers without making it mandatory to install Python, I have to use PyInstaller to pack it into an EXE, but most antivirus programs don't like that kind of stuff. I don't really think the executable contains anything harmful to your computer, but if you still have any concerns, you can install Python on your computer and the libraries I used to write Corvid and run it without packing it into an executable.

**Comment by FrozenDragon0** [comment]
> Corvid is written in Python, so in order to make it work on other people's computers without making it mandatory to install Python, I have to use PyInstaller to pack it into an EXE, but most antivirus programs don't like that kind of stuff. I don't really think the executable contains anything harmful to your computer, but if you still have any concerns, you can install Python on your computer and the libraries I used to write Corvid and run it without packing it into an executable.

Thanks for clarifying, I do also have an old shitty laptop I don't use nor care about anymore, so I suppose I could use that to run the program aswell.

**Comment by kungfooman** [comment]
> Thanks for clarifying, I do also have an old shitty laptop I don't use nor care about anymore, so I suppose I could use that to run the program aswell.

As a rule of thumb, don't trust anything.

- If you use Linux, you can create restricted user accounts e.g. 
- In general use any kind of VM (e.g. VMWare) to run applications, so everything you test/run only has a limited scope of potential harm
- If you use Windows, you can use [SandBoxie](https://sandboxie-plus.com/)

**Comment by FrozenDragon0** [comment]
> > Thanks for clarifying, I do also have an old shitty laptop I don't use nor care about anymore, so I suppose I could use that to run the program aswell.
> 
> As a rule of thumb, don't trust anything.
> 
> * If you use Linux, you can create restricted user accounts e.g.
> * In general use any kind of VM (e.g. VMWare) to run applications, so everything you test/run only has a limited scope of potential harm
> * If you use Windows, you can use [SandBoxie](https://sandboxie-plus.com/)

Fully aware hehe, my bad history of downloading random exe's years ago is what's made me sketch of random exe's now.
