### ISSUE TITLE
Issue generating .map file

### ISSUE THREAD

**Issue by AusNaminator** [KILLTUBE/corvid#32]
I'm trying to convert a Source Mod map and i have received this error.

![Screenshot 2023-10-16 232453](https://github.com/KILLTUBE/corvid/assets/47353628/36236894-13a4-4f23-a26a-753f0612e03d)

**Comment by myuce** [comment]
Some decompiled maps have entities with missing keys, so this error occurs when you try to convert them with Corvid. Could you tell me what map it is and what mod it's from? I may not be able to fix the bug, but I think I can add the necessary keys/values so it won't make Corvid crash.

**Comment by AusNaminator** [comment]
It is the map tls_lockdown from Stargate: The Last Stand (https://www.moddb.com/mods/stargate-the-last-stand)

**Comment by myuce** [comment]
The issue seems to be fixed with the latest changes. You should be able to convert it with the latest pre-release version.
