### ISSUE TITLE
Team Fortress 2 gameDef missing gameRoot

### ISSUE THREAD

**Issue by func-vehicle** [KILLTUBE/corvid#4]
This is a really cool tool. I tried it with a CS:GO map and it worked brilliantly. Then tried a TF2 map and it said a .vpk was invalid. Figured out it was because gameRoot in TF2's gameDef is blank - changing this to "Team Fortress 2" made it work too. Looks like Fistful of Frags has the same issue but I don't know the directory name for it.

**Comment by myuce** [comment]
Added the proper directory names in gameDef.json and update the release. Thanks for letting me know.
