### ISSUE TITLE
Exported asset names sometimes contains spaces, causing errors

### ISSUE THREAD

**Issue by fusorf** [KILLTUBE/corvid#6]
In GDT
![image](https://user-images.githubusercontent.com/40438885/113841495-0e8be280-9792-11eb-9fdc-073a1181ba16.png)

In texture_assets 
![image](https://user-images.githubusercontent.com/40438885/113841695-47c45280-9792-11eb-865d-c868319a937d.png)

map is "c1m3_mall_d" from Left4dead 2

**Comment by myuce** [comment]
I'll have to write a quick fix for those after making sure I included all the invalid characters. Thanks for bringing that to my attention.

**Comment by myuce** [comment]
Should be fixed after 519a6b46d97db73854357eedd2fc264cdec36849.
