### ISSUE TITLE
Models not using correct skin

### ISSUE THREAD

**Issue by func-vehicle** [KILLTUBE/corvid#8]
Seems like the conversion process ignores the skin KVP and exports the prop with skin 0. Here's an example I have from my map.

### Hammer
![HammerView](https://user-images.githubusercontent.com/56104255/113916545-3469c380-9834-11eb-945c-fb0c65821059.PNG)

### Radiant
![RadiantView](https://user-images.githubusercontent.com/56104255/113916577-3e8bc200-9834-11eb-85e8-8f38124c9c4c.PNG)

**Comment by myuce** [comment]
I guess I forgot to mention that those cannot be converted right now. I'll be looking into ways to create duplicate models using the alternative skins the same way I do it with models with the *rendercolor* KVP.

**Comment by myuce** [comment]
Do you happen to have any models that use multiple materials with alternative skins? I'm thinking of working on a fix for this issue today or tomorrow, so I'm looking for examples that can help me see how information related to model skins is stored.

**Comment by snowtyler** [comment]
> Do you happen to have any models that use multiple materials with alternative skins? I'm thinking of working on a fix for this issue today or tomorrow, so I'm looking for examples that can help me see how information related to model skins is stored.

Not the OP of this thread, but I know of a few HL2 models that have multiple skins, one is props_junk\plasticcrate01a.mdl which has about 5 skins in total; another is props_c17\oildrum001.mdl which has about 6 different skins.

**Comment by myuce** [comment]
> Not the OP of this thread, but I know of a few HL2 models that have multiple skins, one is props_junk\plasticcrate01a.mdl which has about 5 skins in total; another is props_c17\oildrum001.mdl which has about 6 different skins.

@snowtyler those models do have several skins, but I'm looking for models that have multiple materials and skins that replace those materials to make sure I don't do anything wrong with them.

**Comment by myuce** [comment]
This issue has been fixed with 978661136576fba38fb1b047a2e283c4774c1024. The new version will be released soon.

As you can see from the screenshots, models with different skins are converted with no problems.
![Hammer](https://user-images.githubusercontent.com/4535623/144113323-562f158a-0db6-4853-ac47-fee544ef75cb.png)
![Radiant](https://user-images.githubusercontent.com/4535623/144113373-482e71d9-bc82-46c0-b610-3dbc9bdf2816.png)
