### ISSUE TITLE
HL2 door models glitch

### ISSUE THREAD

**Issue by snowtyler** [KILLTUBE/corvid#9]
![image](https://user-images.githubusercontent.com/4754415/114446483-471b2a00-9b9f-11eb-9ce4-d3691b3eb8f7.png)

This issue appears to occur on all of the door models in HL2. 

By the way, is there a separate tool that can convert Source models to COD?

**Comment by myuce** [comment]
It is an issue I'm aware of and I also mentioned in the readme file. I suppose you can convert those models to OBJ using [Crafty](https://nemstools.github.io/pages/Crafty.html) and then to XMODEL. The model converter I'm currently using sometimes doesn't give perfect results. It's one of the first things I'll be looking into once I'm sure about all the existing issues.

**Comment by myuce** [comment]
This issue has been fixed with 1cdcdf26bd75297b80affe34df622d90831a875a. I removed the old model converter and wrote a new one using SourceIO's MDL loader. I will release the new version soon with almost all the issues fixed.
